# Generated by Django 5.2.17 on 2026-09-07 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(default='edit', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('format', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('preview', 'Готов к импорту'), ('imported', 'Импортирован'), ('superseded', 'Архив')], default='preview', max_length=20)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(null=True)),
                ('payload', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('receivable_column', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payable_column', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.importbatch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('rows', models.JSONField(default=list)),
                ('columns', models.PositiveIntegerField(default=1)),
                ('formula_count', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='ledger.importbatch')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата')),
                ('direction', models.CharField(choices=[('out', 'Отгрузка'), ('in', 'Приёмка')], default='out', max_length=5, verbose_name='Направление')),
                ('partner', models.CharField(max_length=150, verbose_name='Контрагент')),
                ('vehicle', models.CharField(max_length=150, verbose_name='Номер машины / описание')),
                ('gross', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Брутто, кг')),
                ('tare', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тара, кг')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена, UZS/кг')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('net', models.DecimalField(decimal_places=3, max_digits=14)),
                ('clean', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.importbatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('gross__gte', models.F('tare'))), name='gross_above_tare'), models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='discount_range'), models.CheckConstraint(condition=models.Q(('price__gte', 0), ('tare__gte', 0)), name='positive_delivery_inputs')],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата')),
                ('kind', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма, UZS')),
                ('description', models.CharField(max_length=500, verbose_name='Назначение платежа')),
                ('category', models.CharField(default='Прочее', max_length=80, verbose_name='Категория')),
                ('partner', models.CharField(blank=True, max_length=150, verbose_name='Контрагент')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.importbatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_operation_amount')],
            },
        ),
    ]
