# Generated by Django 5.2.17 on 2026-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='positive_operation_amount',
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Отрицательная сумма означает сторно в выбранном типе операции.', max_digits=20, verbose_name='Сумма, UZS'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='nonzero_operation_amount'),
        ),
    ]
