# Generated by Django 5.2.17 on 2026-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_delivery_clean_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('preview', 'На проверке'), ('imported', 'Импортирован'), ('superseded', 'Архив')], default='preview', max_length=20),
        ),
    ]
