# Generated by Django 5.2.17 on 2026-09-09 09:14

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_importbatch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Контрагент')),
                ('key', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('date', models.DateField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма оплаты, UZS')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('cancelled_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RecordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('record_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='ledger.counterparty'),
        ),
        migrations.AddConstraint(
            model_name='partnerbalance',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='paid_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='partnerbalance',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', django.db.models.functions.math.Abs('balance'))), name='paid_within_debt'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ledger.partnerbalance'),
        ),
        migrations.AddIndex(
            model_name='recordchange',
            index=models.Index(fields=['kind', 'record_id'], name='ledger_reco_kind_754d84_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debt_payment_positive'),
        ),
    ]
