# Generated by Django 5.2.17 on 2026-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_seed_counterparties'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
