# Generated by Django 5.2.17 on 2026-09-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_mark_archived_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('projection', models.JSONField(default=dict)),
                ('ledger_baseline', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('applied_revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='working_book', to='ledger.importbatch')),
            ],
            options={
                'permissions': [('edit_workbook_formulas', 'Can edit workbook formulas and structure')],
            },
        ),
        migrations.CreateModel(
            name='WorkbookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.BinaryField()),
                ('changes', models.JSONField(default=list)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(default='edit', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ledger.workingworkbook')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('workbook', 'revision'), name='unique_workbook_revision')],
            },
        ),
    ]
