# Generated by Django 5.2.17 on 2026-09-17 08:09

import django.db.models.deletion
import ledger.models
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_workspace(apps, schema_editor):
    Workspace = apps.get_model('ledger', 'Workspace')
    Workspace.objects.using(schema_editor.connection.alias).create(pk=1, name='MetalFlow')


def assign_existing_users(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Membership = apps.get_model('ledger', 'WorkspaceMembership')
    db = schema_editor.connection.alias
    Membership.objects.using(db).bulk_create([
        Membership(user_id=user.pk, workspace_id=1, role='owner')
        for user in User.objects.using(db).all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_default_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название компании')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('member', 'Сотрудник')], default='owner', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_default_workspace, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='counterparty',
            name='key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='operation',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='partnerbalance',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='recordchange',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='ledger.workspace'),
        ),
        migrations.AddField(
            model_name='workspacestate',
            name='workspace',
            field=models.ForeignKey(default=ledger.models.default_workspace_id, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='ledger.workspace'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_workspace_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('workspace', 'sha256'), name='unique_workspace_import_hash'),
        ),
        migrations.AddConstraint(
            model_name='workspacestate',
            constraint=models.UniqueConstraint(fields=('workspace',), name='unique_workspace_state'),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.workspace'),
        ),
        migrations.RunPython(assign_existing_users, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WorkbookVersion',
        ),
        migrations.DeleteModel(
            name='WorkingWorkbook',
        ),
    ]
