# Generated by Django 5.2.17 on 2026-09-17 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_client_workspaces_and_remove_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='partnerbalance',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('workspace', 'uid'), name='unique_workspace_delivery_uid'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('workspace', 'uid'), name='unique_workspace_operation_uid'),
        ),
        migrations.AddConstraint(
            model_name='partnerbalance',
            constraint=models.UniqueConstraint(fields=('workspace', 'uid'), name='unique_workspace_debt_uid'),
        ),
    ]
