# Generated by Django 5.2.17 on 2026-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_workspace_scoped_record_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступ активен'),
        ),
    ]
