from django.urls import path
from . import views, debt_views, workbook_views
urlpatterns = [path('', workbook_views.index, name='home'),
    path('summary/', views.dashboard, name='dashboard'),
    path('workbooks/', workbook_views.index, name='workbooks'),
    path('workbooks/create/<int:batch_id>/', workbook_views.create, name='workbook_create'),
    path('workbooks/<int:pk>/', workbook_views.editor, name='workbook_detail'),
    path('workbooks/<int:pk>/data/', workbook_views.data, name='workbook_data'),
    path('workbooks/<int:pk>/save/', workbook_views.save, name='workbook_save'),
    path('workbooks/<int:pk>/finish/', workbook_views.finish, name='workbook_finish'),
    path('workbooks/<int:pk>/history/', workbook_views.history, name='workbook_history'),
    path('workbooks/<int:pk>/versions/<int:version>/', workbook_views.editor, name='workbook_version'),
    path('workbooks/<int:pk>/restore/<int:version>/', workbook_views.restore, name='workbook_restore'),
    path('workbooks/<int:pk>/preview/', workbook_views.preview, name='workbook_preview'),
    path('workbooks/<int:pk>/apply/', workbook_views.apply, name='workbook_apply'),
    path('workbooks/<int:pk>/download/', workbook_views.download, name='workbook_download'),
    path('operations/', views.operations, name='operations'), path('deliveries/', views.deliveries, name='deliveries'),
    path('partners/', debt_views.partners, name='partners'),
    path('partners/<int:pk>/', debt_views.partner_detail, name='partner_detail'),
    path('debts/new/', debt_views.debt_form, name='debt_new'),
    path('debts/<int:pk>/', debt_views.debt_detail, name='debt_detail'),
    path('debts/<int:pk>/edit/', debt_views.debt_form, name='debt_edit'),
    path('debts/<int:pk>/delete/', debt_views.debt_toggle, name='debt_delete'),
    path('debts/<int:pk>/restore/', debt_views.debt_toggle, {'restore': True}, name='debt_restore'),
    path('debts/<int:pk>/pay/', debt_views.payment_new, name='payment_new'),
    path('payments/<int:pk>/cancel/', debt_views.payment_cancel, name='payment_cancel'),
    path('operations/new/', views.record_form, {'kind':'operations'}, name='operation_new'),
    path('deliveries/new/', views.record_form, {'kind':'deliveries'}, name='delivery_new'),
    path('records/<str:kind>/<int:pk>/', views.record_detail, name='record_detail'),
    path('records/<str:kind>/<int:pk>/edit/', views.record_form, name='record_edit'),
    path('records/<str:kind>/<int:pk>/delete/', views.record_delete, name='record_delete'),
    path('records/<str:kind>/<int:pk>/restore/', views.record_delete, {'restore': True}, name='record_restore'),
    path('imports/', views.imports, name='imports'), path('imports/<int:pk>/', views.import_detail, name='import_detail'),
    path('imports/<int:pk>/confirm/', views.import_confirm, name='import_confirm'),
    path('imports/<int:pk>/source/', views.source_download, name='source_download'),
    path('sheets/', views.sheets, name='sheets'), path('sheets/<int:pk>/', views.sheet_detail, name='sheet_detail'),
    path('exports/', views.exports, name='exports'), path('exports/<str:kind>/', views.export_download, name='export_download'),
    path('help/', views.help_page, name='help')]
